version: '3'
services:
  web:
    build: ./
    ports:
    - '9999:80'
    expose:
    - "80"
    volumes:
    - ./:/var/www/html/
    links:
    - postgresql
    environment:
      ENABLE_ENV_FILE: 1
      ENABLE_LOCALCONF: 0
      API_TOKEN: "<YOUR GITHUB API TOKEN>"
  postgresql:
    image: 'postgres'
    ports:
      - '6432:5432'
    container_name: 'yii2-postgresql'
    environment:
      POSTGRESQL_USERNAME: yii2shop
      POSTGRESQL_DATABASE: yii2shop
      POSTGRESQL_PASSWORD: yii2shop
    volumes:
      - ./postgres/data:/VAR/lib/postgresql/data
      - ./import:/home
      - ./import/db.sql:/docker-entrypoint-initdb.d/postgresql.sql


#
#
#
#      docker-compose exec postgresql pg_dump -U postgres postgres > ./import/1dbexport.pgsql
#      docker-compose exec postgresql pg_dump -U postgres -w --dbname postgres > db.sql #import
#      docker-compose exec postgresql psql -U postgres -w -d postgres -f db.sql # export
#
#
#