version: '3'
services:
  web:
    build: ./
    ports:
    - '9999:80'
    expose:
    - "80"
    volumes:
    - ./:/var/www/html/
    links:
    - mysql
    environment:
      ENABLE_ENV_FILE: 1
      ENABLE_LOCALCONF: 0
      API_TOKEN: "<YOUR GITHUB API TOKEN>"
  mysql:
    image: mysql:5.7
    container_name: 'yii2-mysql'
    restart: 'always'
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: yii2shop
      MYSQL_DATABASE: yii2shop
      MYSQL_USER: yii2shop
      MYSQL_PASSWORD: yii2shop
    volumes:
    - ./config/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'yii2-phpmyadmin'
    links:
    - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
    - '9090:80'
    volumes:
    - /sessions

  postgresql:
    image: 'postgres'
    ports:
      - '6432:5432'
    container_name: 'yii2-postgresql'
    environment:
      POSTGRESQL_USERNAME: yii2shop
      POSTGRESQL_DATABASE: yii2shop
      POSTGRESQL_PASSWORD: yii2shop
    volumes:
      - ./postgres/data:/VAR/lib/postgresql/data
      - ./import:/home
